package com.scarface.code.editor

data class LanguageDefinition(val id: String, val title: String, val extensions: List<String>, val keywords: List<String>)
object LanguageCatalog {
    val languages = listOf(
        LanguageDefinition("python", "Python", "py pyw".split(" "), "False None True and as assert async await break class continue def del elif else except finally for from global if import in is lambda nonlocal not or pass raise return try while with yield print range len str int list dict set tuple open input".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("javascript", "JavaScript", "js mjs cjs jsx".split(" "), "async await break case catch class const continue debugger default delete do else export extends false finally for from function if import in instanceof let new null of return static super switch this throw true try typeof var void while yield console".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("typescript", "TypeScript", "ts tsx".split(" "), "abstract any as async await boolean break case catch class const constructor continue declare default else enum export extends false finally for from function if implements import in interface keyof let namespace never new null number of private protected public readonly return static string super switch this throw true try type typeof undefined unknown var void while yield console".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("html", "HTML", "html htm".split(" "), "html head body div span script style link meta title input button form section article main nav header footer a img p".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("css", "CSS", "css scss less".split(" "), "color background display flex grid margin padding border width height position absolute relative font-size font-family align-items justify-content".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("php", "PHP", "php".split(" "), "abstract array as break callable case catch class clone const continue declare default die do echo else elseif empty endfor endforeach endif eval exit extends final finally fn for foreach function global if implements include include_once instanceof interface isset list match namespace new null print private protected public readonly require require_once return static switch throw trait try unset use var while yield".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("c", "C", "c h".split(" "), "auto break case char const continue default do double else enum extern float for goto if inline int long register restrict return short signed sizeof static struct switch typedef union unsigned void volatile while".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("cpp", "C++", "cpp cc cxx hpp hh hxx".split(" "), "alignas alignof asm auto bool break case catch char class concept const constexpr consteval continue co_await co_return co_yield decltype default delete do double else enum explicit export extern false float for friend if inline int long mutable namespace new noexcept nullptr operator override private protected public return short signed sizeof static struct switch template this throw true try typedef typename union unsigned using virtual void volatile while".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("csharp", "C#", "cs".split(" "), "abstract as async await base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using var virtual void volatile while yield".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("java", "Java", "java".split(" "), "abstract assert boolean break byte case catch char class const continue default do double else enum extends final finally float for if implements import instanceof int interface long native new null package private protected public return short static strictfp super switch synchronized this throw throws transient true false try void volatile while var record".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("kotlin", "Kotlin", "kt kts".split(" "), "abstract actual annotation as break by catch class companion const constructor continue data do else enum expect external false final finally for fun if import in infix init inline inner interface internal is lateinit noinline null object open operator out override package private protected public reified return sealed suspend super tailrec this throw true try typealias val var vararg when where while println".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("rust", "Rust", "rs".split(" "), "as async await break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("go", "Go", "go".split(" "), "break case chan const continue default defer else fallthrough for func go goto if import interface map package range return select struct switch type var nil true false".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("swift", "Swift", "swift".split(" "), "actor as associatedtype async await break case catch class continue default defer deinit do else enum extension fallthrough false fileprivate for func guard if import in init inout internal is let nil open operator private protocol public repeat rethrows return self static struct subscript super switch throw throws true try typealias var where while".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("dart", "Dart", "dart".split(" "), "abstract as assert async await break case catch class const continue covariant default deferred do dynamic else enum export extends extension external factory false final finally for Function get hide if implements import in interface is late library mixin new null on operator part required rethrow return set show static super switch sync this throw true try typedef var void while with yield".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("bash", "Bash", "sh bash zsh".split(" "), "if then else elif fi for in do done while until case esac function select time export local readonly return exit echo printf cd pwd mkdir rm cp mv chmod".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("powershell", "PowerShell", "ps1 psm1 psd1".split(" "), "begin break catch class continue data do dynamicparam else elseif end enum exit filter finally for foreach from function if in param process return switch throw trap try until using var while Write-Host Get-Item Set-Content".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("sql", "SQL", "sql".split(" "), "SELECT FROM WHERE JOIN LEFT RIGHT INNER OUTER ON GROUP BY ORDER HAVING LIMIT INSERT INTO VALUES UPDATE SET DELETE CREATE TABLE INDEX DROP ALTER DISTINCT AS AND OR NOT NULL PRIMARY KEY REFERENCES UNION WITH select from where join left right inner outer on group by order having limit insert into values update set delete create table index drop alter distinct as and or not null".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("json", "JSON", "json jsonc".split(" "), "true false null".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("yaml", "YAML", "yaml yml".split(" "), "true false null yes no on off".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("xml", "XML", "xml svg plist".split(" "), "xml version encoding".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("markdown", "Markdown", "md markdown".split(" "), "".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("ruby", "Ruby", "rb".split(" "), "begin break case class def do else elsif end ensure false for if in module next nil rescue return self super then true unless until when while yield".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("lua", "Lua", "lua".split(" "), "and break do else elseif end false for function goto if in local nil not or repeat return then true until while".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("r", "R", "r r".split(" "), "if else repeat while function for in next break TRUE FALSE NULL NA".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("toml", "TOML", "toml".split(" "), "true false".split(" ").filter { it.isNotEmpty() }),
        LanguageDefinition("dockerfile", "Dockerfile", "dockerfile".split(" "), "FROM RUN COPY ADD CMD ENTRYPOINT ENV ARG WORKDIR USER EXPOSE VOLUME LABEL ONBUILD HEALTHCHECK SHELL".split(" ").filter { it.isNotEmpty() }),
    )
    fun forFilename(name: String): LanguageDefinition? {
        val ext = name.substringAfterLast('.', name).lowercase()
        return languages.firstOrNull { ext in it.extensions }
    }
}
